const data = [
  {
    amount: 495,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "fzsh4buo0sueytc",
    impactPerUnit: 0,
    name: "Planting Tree _ Test By Mazin v",
    omr_unit: 33,
    project_prefix: "tree",
    project_type_name: "Planting",
    quantity: 15,
    type: "ew8txwsxjomsuiv",
  },
  {
    amount: 90,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "bjczsx84afi3hex",
    impactPerUnit: 0,
    name: "Project BETA",
    omr_unit: 18,
    project_prefix: "tree",
    project_type_name: "Planting",
    quantity: 5,
    type: "ew8txwsxjomsuiv",
  },
  {
    amount: 1800,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "ijqdhbhlm9xvawj",
    impactPerUnit: 0,
    name: "Project BETA",
    omr_unit: 18,
    project_prefix: "tree",
    project_type_name: "Planting",
    quantity: 100,
    type: "ew8txwsxjomsuiv",
  },
  {
    amount: 450,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "if546wt0444iwz0",
    impactPerUnit: 0,
    name: "Project BETA",
    omr_unit: 18,
    project_prefix: "tree",
    project_type_name: "Planting",
    quantity: 25,
    type: "ew8txwsxjomsuiv",
  },
  {
    amount: 1000,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "gcgy1emb9ov5mcn",
    impactPerUnit: 0,
    name: "STOP ",
    omr_unit: 43,
    project_prefix: "others",
    project_type_name: "Plastic Offset ",
    quantity: 1,
    type: "cai41ibv2bt7buw",
  },
  {
    amount: 900,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "dcpo8vo4tgrrcev",
    impactPerUnit: 0,
    name: "Project BETA",
    omr_unit: 18,
    project_prefix: "tree",
    project_type_name: "Planting",
    quantity: 50,
    type: "ew8txwsxjomsuiv",
  },
  {
    amount: 1000,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "2md0i5m98d0nq3q",
    impactPerUnit: 0,
    name: "STOP ",
    omr_unit: 43,
    project_prefix: "others",
    project_type_name: "Plastic Offset ",
    quantity: 1,
    type: "cai41ibv2bt7buw",
  },
  {
    amount: 60,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "nua5asrl2whetcd",
    impactPerUnit: 0,
    name: "Planting Trees _2",
    omr_unit: 3,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 20,
    type: "2t5cayzas22mj1r",
  },
  {
    amount: 300,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "n9rj1vzidij3twl",
    impactPerUnit: 0,
    name: "Mazin Project In Jalan BB",
    omr_unit: 12,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 25,
    type: "2t5cayzas22mj1r",
  },
  {
    amount: 60,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "smiskh1w2qnytu7",
    impactPerUnit: 0,
    name: "Planting Trees _2",
    omr_unit: 3,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 20,
    type: "2t5cayzas22mj1r",
  },
  {
    amount: 150,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "jyxj8rcg0p00v8v",
    impactPerUnit: 0,
    name: "Planting Trees _2",
    omr_unit: 3,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 50,
    type: "2t5cayzas22mj1r",
  },
  {
    amount: 75,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "c9ida8ri6dhe4wm",
    impactPerUnit: 0,
    name: "Planting Trees _2",
    omr_unit: 3,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 25,
    type: "2t5cayzas22mj1r",
  },
  {
    amount: 275,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "mve802sprypk2fj",
    impactPerUnit: 0,
    name: "Test 1",
    omr_unit: 55,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 5,
    type: "2t5cayzas22mj1r",
  },
  {
    amount: 90,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "7jsp7qjvqcbe8ss",
    impactPerUnit: 0,
    name: "Project BETA",
    omr_unit: 18,
    project_prefix: "tree",
    project_type_name: "Planting",
    quantity: 5,
    type: "ew8txwsxjomsuiv",
  },
  {
    amount: 1375,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "hg79ltj22nry9p1",
    impactPerUnit: 0,
    name: "Test 1",
    omr_unit: 55,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 25,
    type: "2t5cayzas22mj1r",
  },
  {
    amount: 1375,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "o0zynajuuy28poa",
    impactPerUnit: 0,
    name: "Test 1",
    omr_unit: 55,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 25,
    type: "2t5cayzas22mj1r",
  },
  {
    amount: 100,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "2kztfcyr5pbkamo",
    impactPerUnit: 0,
    name: "STOP ",
    omr_unit: 43,
    project_prefix: "others",
    project_type_name: "Plastic Offset ",
    quantity: 1,
    type: "cai41ibv2bt7buw",
  },
  {
    amount: 90,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "7yi6pahmthiuiqq",
    impactPerUnit: 0,
    name: "Project BETA",
    omr_unit: 18,
    project_prefix: "tree",
    project_type_name: "Planting",
    quantity: 5,
    type: "ew8txwsxjomsuiv",
  },
  {
    amount: 150,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "zbvpak5nwsiekm7",
    impactPerUnit: 0,
    name: "Planting Trees _2",
    omr_unit: 3,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 50,
    type: "2t5cayzas22mj1r",
  },
  {
    amount: 150,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "v9w4rj6q7l4jp12",
    impactPerUnit: 0,
    name: "Planting Trees _2",
    omr_unit: 3,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 50,
    type: "2t5cayzas22mj1r",
  },
  {
    amount: 150,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "58uo1ygewbr9lc6",
    impactPerUnit: 10,
    name: "Planting Trees _2",
    omr_unit: 3,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 50,
    type: "2t5cayzas22mj1r",
  },
  {
    amount: 150,
    collectionId: "fqg6idjkeyzutrh",
    collectionName: "test",
    id: "7mveqb132qtxbgl",
    impactPerUnit: 10,
    name: "Planting Trees _2",
    omr_unit: 3,
    project_prefix: "tree",
    project_type_name: "Planting Trees Test ",
    quantity: 50,
    type: "2t5cayzas22mj1r",
  },
];

let output = [];

let filteredProjects = {};

data.forEach((item) => {
  if (filteredProjects[item?.project_type_name || "unknown"]) {
    filteredProjects[item?.project_type_name || "unknown"].push(item);
  } else {
    filteredProjects[item?.project_type_name || "unknown"] = [];
    filteredProjects[item?.project_type_name || "unknown"].push(item);
  }
});

Object.keys(filteredProjects).forEach((key) => {
  output.push({
    name: key,
    impact: filteredProjects[key]
      .map((e) => {
        if (e.project_prefix === "tree") {
          return (e.quantity || 0) * (e.impactPerUnit || 0);
        } else {
          return (e.amount / e.omr_unit) * e.impactPerUnit;
        }
      })
      .reduce((a, b) => a + b, 0),
    projects: filteredProjects[key].length,
  });
});

return output.sort((a, b) => b.impact - a.impact);
