import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavigationOptions from "./_components/NavigationOptions";
import { lora } from "@/lib/font";
import Navbar from "@/components/layout/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.className} ${geistMono.variable} antialiased`}>
        <NavigationOptions />
        <Navbar />
        <div className={geistSans.className}>{children}</div>
        <div className="h-20 md:hidden" />
      </body>
    </html>
  );
}
